version: '3.8'
services:
  app:
    image: test-bank
    container_name: test-bank
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
      - PORT=3000
      - NODE_ENV=development
      - JWT_SECRET=${JWT_SECRET}
  postgres:
    image: postgres
    container_name: postgres-test-bank
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
